import glob
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
import textwrap


def find_latest_trades(n=2):
    files = sorted(glob.glob("logs/v5_15m30d_trades_*.csv"))
    return files[-n:]


def summarize_trades(trades_file):
    df = pd.read_csv(trades_file, parse_dates=["exit_time", "entry_time"])
    initial = None
    final = None
    if "capital_after" in df.columns:
        # assume capital_after is the capital after each trade
        final = float(df["capital_after"].iloc[-1])
        # try to infer initial from first trade
        # but safest is to parse summary file; fallback to 100
        initial = float(df["capital_after"].iloc[0] - df["pnl"].iloc[0]) if len(df) > 0 else 100.0
    else:
        initial = 100.0
        final = initial + df["pnl"].sum()

    total_trades = len(df)
    wins = df[df["pnl"] > 0]
    losses = df[df["pnl"] < 0]
    win_rate = len(wins) / total_trades * 100 if total_trades > 0 else 0
    avg_win = wins["pnl"].mean() if len(wins) > 0 else 0
    avg_loss = abs(losses["pnl"].mean()) if len(losses) > 0 else 0

    return {
        "file": trades_file,
        "d": df,
        "initial": initial,
        "final": final,
        "total_trades": total_trades,
        "win_rate": win_rate,
        "avg_win": avg_win,
        "avg_loss": avg_loss,
        "total_pnl": df["pnl"].sum(),
    }


def plot_equity(curves, out_png):
    plt.figure(figsize=(8, 4))
    for label, series in curves.items():
        plt.plot(series["time"], series["capital"], label=label)
    plt.xlabel("Time")
    plt.ylabel("Capital (USDT)")
    plt.legend()
    plt.tight_layout()
    plt.savefig(out_png)
    print("Saved equity plot:", out_png)


def plot_trade_pnl(dfs, out_png):
    plt.figure(figsize=(8, 4))
    for label, df in dfs.items():
        plt.bar(df["exit_time"].dt.to_pydatetime(), df["pnl"], label=label, alpha=0.7)
    plt.xlabel("Exit Time")
    plt.ylabel("PnL (USDT)")
    plt.tight_layout()
    plt.savefig(out_png)
    print("Saved trades plot:", out_png)


def generate_report(summaries, out_md, out_equity_png, out_trades_png, pr_draft):
    curves = {}
    dfs_for_plot = {}
    for s in summaries:
        df = s["d"].copy()
        # use exit_time and capital_after for equity curve; if missing, build cumulative
        if "capital_after" in df.columns:
            cap = df[["exit_time", "capital_after"]].copy()
            cap = cap.sort_values("exit_time")
            curves[Path(s["file"]).stem] = {"time": cap["exit_time"], "capital": cap["capital_after"]}
        else:
            cum = (s["initial"] + df["pnl"].cumsum()).reset_index(drop=True)
            times = pd.to_datetime(df["exit_time"])
            curves[Path(s["file"]).stem] = {"time": times, "capital": cum}

        dfs_for_plot[Path(s["file"]).stem] = df

    Path("logs").mkdir(parents=True, exist_ok=True)
    plot_equity(curves, out_equity_png)
    plot_trade_pnl(dfs_for_plot, out_trades_png)

    # build markdown
    lines = []
    lines.append("# Backtest comparison report")
    lines.append("")
    lines.append("Generated by scripts/generate_backtest_comparison_report.py")
    lines.append("")
    for s in summaries:
        lines.append(f"## {Path(s['file']).name}")
        lines.append("")
        lines.append(f"- Total trades: {s['total_trades']}")
        lines.append(f"- Final capital: {s['final']:.2f} USDT")
        lines.append(f"- Total PnL: {s['total_pnl']:.2f} USDT")
        lines.append(f"- Win rate: {s['win_rate']:.2f}%")
        lines.append(f"- Avg win: {s['avg_win']:.2f} USDT")
        lines.append(f"- Avg loss: {s['avg_loss']:.2f} USDT")
        lines.append("")

    lines.append("## Equity curve")
    lines.append(f"![equity](../{out_equity_png})")
    lines.append("")
    lines.append("## Trades PnL")
    lines.append(f"![trades](../{out_trades_png})")
    lines.append("")
    lines.append("---")
    lines.append("## Notes and recommendations")
    lines.append("")
    lines.append(
        textwrap.dedent("""
    - 放宽 `trading.max_stop_loss_abs`（或对应回测止损）在本样本上能将短期亏损转换为更高的正收益，但同时带来更高的最大回撤。
    - 建议：在把更宽止损推广到实盘前，先对更长时间和更多标的进行样本外验证，并对最大回撤与连续亏损阈值进行联动调整（例如增加冷却期或降低仓位百分比）。
    - 如果接受更高回撤，请考虑同时增加 `trailing_stop` 与 `time_stop` 或降低 `position_percent` 以控制回撤风险。
    """)
    )

    Path(out_md).write_text("\n".join(lines), encoding="utf-8")
    print("Saved report:", out_md)

    # PR draft
    pr_lines = []
    pr_lines.append("# PR: Adjust stop-loss configuration experiments")
    pr_lines.append("")
    pr_lines.append("This PR contains:")
    pr_lines.append("- Investigation comparing baseline stop-loss (0.6%) vs relaxed stop-loss (2%) on SOLUSDT sample")
    pr_lines.append("- Generated backtest comparison report and plots in `logs/` and `docs/`")
    pr_lines.append("")
    pr_lines.append("Summary:")
    pr_lines.append("- Baseline final capital: {:.2f} USDT".format(summaries[0]["final"]))
    pr_lines.append("- Relaxed stop-loss final capital: {:.2f} USDT".format(summaries[1]["final"]))
    pr_lines.append("")
    pr_lines.append(
        "Recommended next steps: run parameter grid search and out-of-sample validation before applying changes to live config."
    )
    Path(pr_draft).write_text("\n".join(pr_lines), encoding="utf-8")
    print("Saved PR draft:", pr_draft)


def main():
    trades = find_latest_trades(2)
    if len(trades) < 2:
        print("Need at least two trade log files in logs/ to compare.")
        return 1

    summaries = [summarize_trades(t) for t in trades]
    out_md = "docs/backtest_comparison_report.md"
    out_equity_png = "logs/backtest_comparison_equity.png"
    out_trades_png = "logs/backtest_comparison_trades.png"
    pr_draft = "PR_DRAFT_stop_loss_experiment.md"
    Path("docs").mkdir(parents=True, exist_ok=True)
    generate_report(summaries, out_md, out_equity_png, out_trades_png, pr_draft)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
